// src/app/components/services-section/services-section.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

interface Service {
  key: string;
  title: string;
  description: string;
  icon: string;
  color: 'primary' | 'secondary' | 'tertiary';
  href: string;
}

@Component({
  selector: 'app-services-section',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './services-section.component.html',
  styleUrl: './services-section.component.css'
})
export class ServicesSectionComponent {
  @Input() locale: string = 'tr';

  services: Service[] = [
    {
      key: 'checkup',
      title: 'Rutin Kontroller',
      description: 'Büyüme ve gelişim takibi, periyodik muayeneler',
      icon: 'fact_check',
      color: 'primary',
      href: '/hizmetlerimiz/rutin-kontroller'
    },
    {
      key: 'vaccination',
      title: 'Aşılama',
      description: 'Sağlık Bakanlığı aşı takvimi ve özel aşılar',
      icon: 'vaccines',
      color: 'secondary',
      href: '/hizmetlerimiz/asilama'
    },
    {
      key: 'illness',
      title: 'Hastalık Tedavisi',
      description: 'Akut ve kronik çocuk hastalıklarının tanı ve tedavisi',
      icon: 'medical_services',
      color: 'tertiary',
      href: '/hizmetlerimiz/hastalik-tedavisi'
    },
    {
      key: 'nutrition',
      title: 'Beslenme Danışmanlığı',
      description: 'Anne sütü, ek gıda ve beslenme programları',
      icon: 'restaurant',
      color: 'primary',
      href: '/hizmetlerimiz/beslenme-danismanligi'
    },
    {
      key: 'development',
      title: 'Gelişim Değerlendirmesi',
      description: 'Fiziksel ve zihinsel gelişim takibi',
      icon: 'trending_up',
      color: 'secondary',
      href: '/hizmetlerimiz/gelisim-degerlendirmesi'
    },
    {
      key: 'sleep',
      title: 'Uyku Danışmanlığı',
      description: 'Bebek ve çocuk uyku sorunlarına çözüm',
      icon: 'bedtime',
      color: 'tertiary',
      href: '/hizmetlerimiz/uyku-danismanligi'
    }
  ];
}
<section class="services-section" aria-labelledby="services-section-title">
  <div class="container md3-container">
    <div class="section-header">
      <span class="section-label">{{ 'SERVICES.SECTION_TITLE' | translate }}</span>
      <h2 id="services-section-title" class="section-title">{{ 'SERVICES.SUBTITLE' | translate }}</h2>
      <p class="section-description">{{ 'SERVICES.SECTION_DESC' | translate }}</p>
    </div>

    <div class="services-grid">
      @for (service of services; track service.key) {
        <div class="service-card" [attr.data-service-color]="service.color">
          <a [routerLink]="service.href" class="service-link">
            <div class="service-icon-wrapper" aria-hidden="true">
              @switch (service.key) {
                @case ('bright-futures') {
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="service-icon-svg">
                    <circle cx="18" cy="10" r="4" />
                    <path d="M14 16 C10 20, 9 28, 12 34 C13 36, 15 37, 18 37" />
                    <path d="M22 16 C24 19, 25 22, 25 26" />
                    <path d="M14 22 C14 26, 16 29, 22 30 C25 30, 27 28, 27 25" />
                    <path d="M18 24 C19 22, 22 21, 24 22 C26 23, 26 26, 24 27 C22 28, 19 27, 18 25" />
                    <circle cx="24" cy="23" r="2.5" />
                    <path d="M16 28 C18 31, 22 32, 25 30" />
                    <path class="accent" d="M33 12 C33 10, 35 8, 37 10 C39 8, 41 10, 41 12 C41 15, 37 18, 37 18 C37 18, 33 15, 33 12Z" fill="currentColor" stroke="none" opacity="0.3" />
                  </svg>
                }
                @case ('triple-p') {
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="service-icon-svg">
                    <circle cx="24" cy="24" r="14" stroke-dasharray="4 3" opacity="0.4" />
                    <circle cx="13" cy="16" r="3.5" />
                    <path d="M10 21 C9 24, 10 27, 13 28 C14 28.5, 15 28, 16 27" />
                    <circle cx="35" cy="16" r="3.5" />
                    <path d="M38 21 C39 24, 38 27, 35 28 C34 28.5, 33 28, 32 27" />
                    <circle cx="24" cy="33" r="3" />
                    <path d="M21 37 C21 39, 22.5 40, 24 40 C25.5 40, 27 39, 27 37" />
                    <path d="M15 26 C18 30, 20 32, 21 33" />
                    <path d="M33 26 C30 30, 28 32, 27 33" />
                    <circle class="accent" cx="24" cy="24" r="3" fill="currentColor" stroke="none" opacity="0.25" />
                  </svg>
                }
                @case ('sleep') {
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="service-icon-svg">
                    <path d="M20 8 C12 10, 8 18, 10 26 C12 34, 20 38, 28 36 C22 34, 18 28, 18 22 C18 16, 20 11, 24 8 C22.5 7.5, 21 7.8, 20 8Z" />
                    <path class="accent" d="M34 10 L35.5 13 L34 16 L32.5 13Z" fill="currentColor" stroke="none" opacity="0.35" />
                    <path class="accent" d="M38 20 L39.2 22.5 L38 25 L36.8 22.5Z" fill="currentColor" stroke="none" opacity="0.25" />
                    <path class="accent" d="M32 17 L33 19 L32 21 L31 19Z" fill="currentColor" stroke="none" opacity="0.3" />
                    <line x1="34" y1="8" x2="34" y2="6" opacity="0.5" />
                    <line x1="36.5" y1="10" x2="38" y2="9" opacity="0.5" />
                    <line x1="40" y1="20" x2="42" y2="19.5" opacity="0.4" />
                    <path d="M10 38 C10 36, 14 34, 18 35 C20 33, 24 33, 26 35 C28 34, 32 34, 34 36 C36 37, 36 39, 34 40 L10 40 C8 39, 8 37, 10 38Z" opacity="0.5" />
                  </svg>
                }
                @case ('lab') {
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="service-icon-svg">
                    <path d="M18 6 L18 12 C18 13, 19 14, 20 14 L24 14 C25 14, 26 13, 26 12 L26 6" />
                    <line x1="16" y1="6" x2="28" y2="6" />
                    <path d="M22 14 L22 18 C22 19, 22 20, 21 21 L16 30" />
                    <path d="M22 18 C23 19, 24 20, 24 22 L28 30" />
                    <circle cx="22" cy="32" r="3" />
                    <line x1="14" y1="35" x2="30" y2="35" stroke-width="1.5" />
                    <path d="M28 14 C32 16, 34 20, 34 26 L34 38" />
                    <path d="M14 40 C14 38, 16 38, 22 38 L34 38 C36 38, 38 38, 38 40" />
                    <line x1="12" y1="40" x2="40" y2="40" />
                    <circle cx="34" cy="28" r="2" stroke-width="1.5" />
                    <path class="accent" d="M20 8 C20 7.2, 20.8 6.5, 21.5 7.2 C22.2 6.5, 23 7.2, 23 8 C23 9, 21.5 10.5, 21.5 10.5 C21.5 10.5, 20 9, 20 8Z" fill="currentColor" stroke="none" opacity="0.35" />
                  </svg>
                }
                @case ('vaccination') {
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="service-icon-svg">
                    <path d="M24 6 C18 6, 10 8, 8 10 C8 22, 10 30, 16 36 C20 40, 24 42, 24 42 C24 42, 28 40, 32 36 C38 30, 40 22, 40 10 C38 8, 30 6, 24 6Z" />
                    <path class="accent" d="M24 10 C20 10, 14 11.5, 12 13 C12 22, 13.5 28, 18 33 C21 36, 24 38, 24 38 C24 38, 27 36, 30 33 C34.5 28, 36 22, 36 13 C34 11.5, 28 10, 24 10Z" fill="currentColor" stroke="none" opacity="0.12" />
                    <path d="M24 18 C24 18, 20 24, 20 27 C20 29.5, 21.8 31, 24 31 C26.2 31, 28 29.5, 28 27 C28 24, 24 18, 24 18Z" />
                    <circle cx="22.5" cy="25.5" r="1" fill="currentColor" stroke="none" opacity="0.2" />
                    <line x1="24" y1="13" x2="24" y2="17" stroke-width="1.5" />
                    <line x1="22" y1="15" x2="26" y2="15" stroke-width="1.5" />
                  </svg>
                }
                @case ('development') {
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="service-icon-svg">
                    <path d="M10 40 L10 10 C10 9, 10.5 8, 12 8 L16 8 C17.5 8, 18 9, 18 10 L18 40" />
                    <line x1="10" y1="14" x2="13" y2="14" stroke-width="1.5" />
                    <line x1="10" y1="19" x2="14" y2="19" stroke-width="1.5" />
                    <line x1="10" y1="24" x2="13" y2="24" stroke-width="1.5" />
                    <line x1="10" y1="29" x2="14" y2="29" stroke-width="1.5" />
                    <line x1="10" y1="34" x2="13" y2="34" stroke-width="1.5" />
                    <line x1="8" y1="40" x2="20" y2="40" />
                    <path d="M28 38 C28 34, 27 28, 28 22 C29 16, 31 12, 34 8" />
                    <path d="M30 12 L34 8 L37 13" />
                    <circle cx="28" cy="34" r="1" fill="currentColor" stroke="none" opacity="0.2" />
                    <circle cx="28" cy="28" r="1.2" fill="currentColor" stroke="none" opacity="0.25" />
                    <circle cx="29" cy="22" r="1.4" fill="currentColor" stroke="none" opacity="0.3" />
                    <circle class="accent" cx="34" cy="8" r="3" fill="currentColor" stroke="none" opacity="0.25" />
                  </svg>
                }
              }
            </div>
            <div class="service-content">
              <h3 class="service-title">{{ service.titleKey | translate }}</h3>
              <hr class="service-divider" aria-hidden="true" role="presentation" />
              <p class="service-description">{{ service.descriptionKey | translate }}</p>
            </div>
            <div class="card-footer">
              <span class="details-link">{{ 'COMMON.DETAILS' | translate }} &rarr;</span>
            </div>
          </a>
        </div>
      }
    </div>

    <div class="section-cta">
      <a routerLink="/hizmetlerimiz" class="cta-button">
        <span>{{ 'SERVICES.VIEW_ALL' | translate }}</span>
      </a>
    </div>
  </div>
</section>

// src/components/sections/ServicesSection.tsx
'use client'

import React from 'react'
import Link from 'next/link'

interface ServicesSectionProps {
  locale: string
}

const ServicesSection: React.FC<ServicesSectionProps> = ({ locale = 'tr' }) => {
  const services = [
    {
      key: 'checkup',
      title: 'Rutin Kontroller',
      description: 'Büyüme ve gelişim takibi, periyodik muayeneler',
      icon: (
        <svg className="service-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      ),
      color: 'primary',
      href: '/hizmetlerimiz/rutin-kontroller'
    },
    {
      key: 'vaccination',
      title: 'Aşılama',
      description: 'Sağlık Bakanlığı aşı takvimi ve özel aşılar',
      icon: (
        <svg className="service-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
        </svg>
      ),
      color: 'secondary',
      href: '/hizmetlerimiz/asilama'
    },
    {
      key: 'illness',
      title: 'Hastalık Tedavisi',
      description: 'Akut ve kronik çocuk hastalıklarının tanı ve tedavisi',
      icon: (
        <svg className="service-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
      ),
      color: 'tertiary',
      href: '/hizmetlerimiz/hastalik-tedavisi'
    },
    {
      key: 'nutrition',
      title: 'Beslenme Danışmanlığı',
      description: 'Anne sütü, ek gıda ve beslenme programları',
      icon: (
        <svg className="service-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
        </svg>
      ),
      color: 'primary',
      href: '/hizmetlerimiz/beslenme-danismanligi'
    },
    {
      key: 'development',
      title: 'Gelişim Değerlendirmesi',
      description: 'Fiziksel ve zihinsel gelişim takibi',
      icon: (
        <svg className="service-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      ),
      color: 'secondary',
      href: '/hizmetlerimiz/gelisim-degerlendirmesi'
    },
    {
      key: 'sleep',
      title: 'Uyku Danışmanlığı',
      description: 'Bebek ve çocuk uyku sorunlarına çözüm',
      icon: (
        <svg className="service-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
        </svg>
      ),
      color: 'tertiary',
      href: '/hizmetlerimiz/uyku-danismanligi'
    }
  ]

  return (
    <section className="services-section">
      <div className="container">
        {/* Section Header */}
        <div className="section-header">
          <h2 className="md-sys-typescale-display-small">Hizmetlerimiz</h2>
          <p className="md-sys-typescale-body-large">
            Çocuğunuzun sağlığı için kapsamlı pediatri hizmetleri
          </p>
        </div>

        {/* Services Grid */}
        <div className="services-grid">
          {services.map((service) => (
            <div key={service.key} className={`service-card service-card--${service.color}`}>
              <div className="service-icon-wrapper">
                {service.icon}
              </div>
              
              <h3 className="service-title">{service.title}</h3>
              <p className="service-description">{service.description}</p>
              
              <Link href={service.href} className="service-link">
                <span>Detaylı Bilgi</span>
                <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </Link>
            </div>
          ))}
        </div>

        {/* CTA Button */}
        <div className="section-footer">
          <Link href="/hizmetlerimiz" className="md-button md-button--filled md-button--large">
            <span>Tüm Hizmetleri Görüntüle</span>
            <svg width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </Link>
        </div>
      </div>

      <style jsx>{`
        .services-section {
          padding: 80px 0;
          background: var(--md-sys-color-surface);
          position: relative;
          overflow: hidden;
        }

        .services-section::before {
          content: '';
          position: absolute;
          top: 0;
          left: 50%;
          transform: translateX(-50%);
          width: 200%;
          height: 100%;
          background: radial-gradient(
            ellipse at center,
            var(--md-sys-color-primary-container) 0%,
            transparent 70%
          );
          opacity: 0.1;
          pointer-events: none;
        }

        .container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 24px;
          position: relative;
        }

        /* Section Header */
        .section-header {
          text-align: center;
          margin-bottom: 56px;
        }

        .section-header h2 {
          color: var(--md-sys-color-on-surface);
          margin-bottom: 16px;
        }

        .section-header p {
          color: var(--md-sys-color-on-surface-variant);
          max-width: 600px;
          margin: 0 auto;
        }

        /* Services Grid */
        .services-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
          gap: 24px;
          margin-bottom: 56px;
        }

        @media (min-width: 768px) {
          .services-grid {
            grid-template-columns: repeat(2, 1fr);
          }
        }

        @media (min-width: 1024px) {
          .services-grid {
            grid-template-columns: repeat(3, 1fr);
          }
        }

        /* Service Card */
        .service-card {
          background: var(--md-sys-color-surface-container);
          border-radius: var(--md-sys-shape-corner-large);
          padding: 32px 24px;
          text-align: center;
          transition: all var(--md-sys-motion-duration-medium2) var(--md-sys-motion-easing-emphasized);
          position: relative;
          overflow: hidden;
        }

        .service-card::before {
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          height: 4px;
          background: var(--md-sys-color-primary);
          transform: scaleX(0);
          transform-origin: left;
          transition: transform var(--md-sys-motion-duration-medium2) var(--md-sys-motion-easing-emphasized);
        }

        .service-card:hover {
          transform: translateY(-4px);
          box-shadow: var(--md-sys-elevation-level3);
        }

        .service-card:hover::before {
          transform: scaleX(1);
        }

        .service-card--secondary::before {
          background: var(--md-sys-color-secondary);
        }

        .service-card--tertiary::before {
          background: var(--md-sys-color-tertiary);
        }

        /* Service Icon */
        .service-icon-wrapper {
          width: 64px;
          height: 64px;
          margin: 0 auto 24px;
          background: var(--md-sys-color-primary-container);
          border-radius: var(--md-sys-shape-corner-large);
          display: flex;
          align-items: center;
          justify-content: center;
          transition: all var(--md-sys-motion-duration-short4) var(--md-sys-motion-easing-standard);
        }

        .service-card--secondary .service-icon-wrapper {
          background: var(--md-sys-color-secondary-container);
        }

        .service-card--tertiary .service-icon-wrapper {
          background: var(--md-sys-color-tertiary-container);
        }

        .service-card:hover .service-icon-wrapper {
          transform: scale(1.1);
        }

        .service-icon {
          width: 32px;
          height: 32px;
          color: var(--md-sys-color-on-primary-container);
        }

        .service-card--secondary .service-icon {
          color: var(--md-sys-color-on-secondary-container);
        }

        .service-card--tertiary .service-icon {
          color: var(--md-sys-color-on-tertiary-container);
        }

        /* Service Content */
        .service-title {
          font-size: 20px;
          font-weight: 600;
          color: var(--md-sys-color-on-surface);
          margin-bottom: 12px;
        }

        .service-description {
          font-size: 14px;
          color: var(--md-sys-color-on-surface-variant);
          line-height: 1.5;
          margin-bottom: 24px;
        }

        /* Service Link */
        .service-link {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          color: var(--md-sys-color-primary);
          text-decoration: none;
          font-size: 14px;
          font-weight: 500;
          padding: 8px 16px;
          border-radius: var(--md-sys-shape-corner-full);
          transition: all var(--md-sys-motion-duration-short3) var(--md-sys-motion-easing-standard);
        }

        .service-link:hover {
          background: var(--md-sys-color-primary-container);
          color: var(--md-sys-color-on-primary-container);
        }

        .service-link svg {
          transition: transform var(--md-sys-motion-duration-short3) var(--md-sys-motion-easing-standard);
        }

        .service-link:hover svg {
          transform: translateX(4px);
        }

        /* Section Footer */
        .section-footer {
          text-align: center;
        }

        /* MD Button Styles */
        .md-button {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 0 24px;
          height: 40px;
          border: none;
          border-radius: var(--md-sys-shape-corner-full);
          font-size: 14px;
          font-weight: 500;
          text-decoration: none;
          cursor: pointer;
          transition: all var(--md-sys-motion-duration-short3) var(--md-sys-motion-easing-standard);
          position: relative;
          overflow: hidden;
        }

        .md-button--filled {
          background: var(--md-sys-color-primary);
          color: var(--md-sys-color-on-primary);
        }

        .md-button--filled:hover {
          box-shadow: var(--md-sys-elevation-level2);
        }

        .md-button--large {
          height: 56px;
          padding: 0 32px;
          font-size: 16px;
        }

        /* Responsive */
        @media (max-width: 768px) {
          .services-section {
            padding: 60px 0;
          }

          .services-grid {
            grid-template-columns: 1fr;
            gap: 20px;
          }

          .section-header {
            margin-bottom: 40px;
          }

          .section-header h2 {
            font-size: 32px;
          }
        }
      `}</style>
    </section>
  )
}

export { ServicesSection }
