// src/app/components/header/header.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AppointmentModalComponent } from '../appointment-modal/appointment-modal.component';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule, AppointmentModalComponent, TranslateModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent implements OnInit, OnDestroy {
  @Input() locale: string = 'tr';
  @Output() localeChange = new EventEmitter<string>();
  
  private translate = inject(TranslateService);
  
  isMobileMenuOpen = false;
  isScrolled = false;
  activeDropdown: string | null = null;
  isAnimating = false;
  isAppointmentModalOpen = false;

  contactInfo = {
    phone: '+90 216 688 44 83',
    email: 'klinik@drmurzoglu.com',
    address: 'Ataşehir, İstanbul'
  };

  navigation: any[] = [
    {
      labelKey: 'HEADER.NAV_ABOUT',
      href: '/hakkimizda',
      children: [
        { labelKey: 'HEADER.NAV_ABOUT_US', href: '/hakkimizda' },
        { labelKey: 'HEADER.NAV_DR_OZLEM', href: '/hakkimizda/dr-ozlem-murzoglu' },
        { labelKey: 'HEADER.NAV_CLINIC_DESIGN', href: '/hakkimizda/klinik-tasarimi' },
        { labelKey: 'HEADER.NAV_FAQ', href: '/hakkimizda/sss' }
      ]
    },
    {
      labelKey: 'HEADER.NAV_SERVICES',
      href: '/hizmetlerimiz',
      children: [
        { labelKey: 'SERVICES.SERVICE_LAB.TITLE', href: '/hizmetlerimiz/laboratuvar-goruntuleme' },
        { labelKey: 'SERVICES.SERVICE_TRIPLE_P.TITLE', href: '/hizmetlerimiz/triple-p' },
        { labelKey: 'SERVICES.SERVICE_SLEEP.TITLE', href: '/hizmetlerimiz/saglikli-uykular' },
        { labelKey: 'SERVICES.SERVICE_BRIGHT_FUTURES.TITLE', href: '/hizmetlerimiz/bright-futures-program' }
      ]
    },
    {
      labelKey: 'HEADER.NAV_INFO_CENTER',
      href: '/bilgi-merkezi',
      children: [
        { label: 'Tüm Kaynaklar', href: '/bilgi-merkezi' },
        { label: 'Aşı Bilgileri', href: '/bilgi-merkezi/asilar' },
        { label: 'Gelişim Rehberleri', href: '/bilgi-merkezi/gelisim-rehberleri' },
        { label: 'Genel Bilgiler', href: '/bilgi-merkezi/genel-bilgiler' },
        { label: 'Büyüme Eğrileri', href: '/bilgi-merkezi/cdc-buyume-egrileri' },
        { label: 'Aile Medya Planı', href: '/bilgi-merkezi/aile-medya-plani' }
      ]
    },
    {
      label: 'Bright Futures™ Yolculuğu',
      href: '/bilgi-merkezi/bright-futures-yolculugu'
    },
    {
      label: 'saygıyla',
      href: '/saygiyla'
    },
    {
      labelKey: 'HEADER.NAV_CONTACT',
      href: '/iletisim'
    }
  ];

  get primaryMenu() {
    return this.navigation;
  }

  ngOnInit() {
    if (typeof window !== 'undefined') {
      window.addEventListener('scroll', this.handleScroll.bind(this));
    }
    
    // Set the current language
    this.translate.use(this.locale);
  }

  ngOnDestroy() {
    if (typeof window !== 'undefined') {
      window.removeEventListener('scroll', this.handleScroll.bind(this));
    }
  }

  handleScroll() {
    this.isScrolled = window.scrollY > 10;
  }

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
    if (typeof document !== 'undefined') {
      document.body.style.overflow = this.isMobileMenuOpen ? 'hidden' : '';
    }
  }

  setActiveDropdown(label: string | null) {
    this.activeDropdown = label;
  }

  handleLanguageChange() {
    this.isAnimating = true;
    
    setTimeout(() => {
      this.locale = this.locale === 'tr' ? 'en' : 'tr';
      this.localeChange.emit(this.locale);
      this.translate.use(this.locale);
      this.isAnimating = false;
    }, 200);
  }
  
  switchLanguage(lang: string) {
    this.locale = lang;
    this.localeChange.emit(lang);
    this.translate.use(lang);
  }

  openAppointmentModal() {
    this.isAppointmentModalOpen = true;
    // Close mobile menu if open
    this.isMobileMenuOpen = false;
    if (typeof document !== 'undefined') {
      document.body.style.overflow = 'hidden';
    }
  }

  closeAppointmentModal() {
    this.isAppointmentModalOpen = false;
    if (typeof document !== 'undefined') {
      document.body.style.overflow = '';
    }
  }
}
<header [ngClass]="{'modern-header': true, 'scrolled': isScrolled}">
  <!-- Top Info Bar - Enhanced -->
  <div class="top-bar">
    <div class="container">
      <div class="top-bar-content">
        <div class="contact-info">
          <a [href]="'tel:' + contactInfo.phone" class="contact-link">
            <span class="icon-wrapper">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <path d="M20 15.5c-1.25 0-2.45-.2-3.57-.57a1.02 1.02 0 00-1.02.24l-2.2 2.2a15.045 15.045 0 01-6.59-6.59l2.2-2.21c.28-.26.36-.65.25-1.01A11.36 11.36 0 018.5 4c0-.55-.45-1-1-1H4c-.55 0-1 .45-1 1 0 9.39 7.61 17 17 17 .55 0 1-.45 1-1v-3.5c0-.55-.45-1-1-1z"/>
              </svg>
            </span>
            <span class="contact-text">{{ contactInfo.phone }}</span>
          </a>
          <span class="separator">|</span>
          <a href="https://api.whatsapp.com/send?phone=905466884483&text=Merhaba%2C%20WhatsApp%20bilgilerinizi%20web%20sitenizden%20ald%C4%B1m." target="_blank" rel="noopener noreferrer" class="contact-link whatsapp-link">
            <span class="icon-wrapper">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12.04 2c-5.46 0-9.91 4.45-9.91 9.91 0 1.75.46 3.45 1.32 4.95L2.05 22l5.25-1.38c1.45.79 3.08 1.21 4.74 1.21 5.46 0 9.91-4.45 9.91-9.91 0-2.65-1.03-5.14-2.9-7.01A9.816 9.816 0 0012.04 2zm.01 18.15c-1.48 0-2.93-.4-4.2-1.15l-.3-.18-3.12.82.83-3.04-.2-.31a8.264 8.264 0 01-1.26-4.38c0-4.54 3.7-8.24 8.24-8.24 2.2 0 4.27.86 5.82 2.42a8.183 8.183 0 012.41 5.83c.02 4.54-3.68 8.23-8.22 8.23zm4.52-6.16c-.25-.12-1.47-.72-1.69-.81-.23-.08-.39-.12-.56.12-.17.25-.64.81-.78.97-.14.17-.29.19-.54.06-.25-.12-1.05-.39-1.99-1.23-.74-.66-1.23-1.47-1.38-1.72-.14-.25-.02-.38.11-.51.11-.11.25-.29.37-.43s.17-.25.25-.41c.08-.17.04-.31-.02-.43s-.56-1.34-.76-1.84c-.2-.48-.41-.42-.56-.43h-.48c-.17 0-.43.06-.66.31-.22.25-.86.85-.86 2.07 0 1.22.89 2.4 1.01 2.56.12.17 1.75 2.67 4.23 3.74.59.26 1.05.41 1.41.52.59.19 1.13.16 1.56.1.48-.07 1.47-.6 1.67-1.18.21-.58.21-1.07.14-1.18s-.22-.16-.47-.28z"/>
              </svg>
            </span>
            <span class="contact-text">{{ 'HEADER.WHATSAPP' | translate }}</span>
          </a>
          <span class="separator">|</span>
          <a href="https://g.co/kgs/jXU64C" target="_blank" rel="noopener noreferrer" class="contact-link google-link">
            <span class="icon-wrapper">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
              </svg>
            </span>
            <span class="contact-text">{{ 'HEADER.GOOGLE_BUSINESS' | translate }}</span>
          </a>
          <span class="separator">|</span>
          <div class="location-info">
            <span class="icon-wrapper">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/>
              </svg>
            </span>
            <span class="contact-text">{{ contactInfo.address }}</span>
          </div>
        </div>
        <a href="https://saglikpetegim.com" target="_blank" rel="noopener noreferrer" class="portal-link">
          <span class="portal-icon">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
            </svg>
          </span>
          <span>{{ 'HEADER.HEALTH_PORTAL' | translate }}</span>
          <span class="arrow">→</span>
        </a>
      </div>
    </div>
  </div>

  <!-- Main Navigation -->
  <nav class="main-nav">
    <div class="container">
      <div class="nav-content">
        <!-- Logo -->
        <a href="/" class="logo">
          <img 
            src="/logos/OM-Wide-Color.svg" 
            alt="Dr. Özlem Murzoğlu" 
            class="logo-wide"
          />
          <img 
            src="/logos/OM-Icon-Color.svg" 
            alt="Dr. Özlem Murzoğlu" 
            class="logo-icon"
          />
        </a>

        <!-- Center Menu - Horizontal -->
        <div class="nav-menu">
          <div *ngFor="let item of primaryMenu" 
               class="nav-item"
               (mouseenter)="item.children && setActiveDropdown(item.labelKey || item.label)"
               (mouseleave)="setActiveDropdown(null)">
            <a [href]="item.href" class="nav-link">
              {{ item.labelKey ? (item.labelKey | translate) : item.label }}
              <svg *ngIf="item.children" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" class="dropdown-icon">
                <path d="M7 10l5 5 5-5z"/>
              </svg>
            </a>
            
            <!-- Dropdown Menu -->
            <div *ngIf="item.children && activeDropdown === (item.labelKey || item.label)" class="dropdown-menu">
              <a *ngFor="let child of item.children"
                 [href]="child.href"
                 class="dropdown-link">
                {{ child.labelKey ? (child.labelKey | translate) : child.label }}
              </a>
            </div>
          </div>
        </div>

        <!-- Right Actions -->
        <div class="nav-actions">
          <!-- Language Switcher -->
          <div class="language-switcher">
            <button 
              [ngClass]="{'switch-button': true, 'en-active': locale === 'en', 'animating': isAnimating}"
              (click)="handleLanguageChange()"
              aria-label="Change language">
              <span class="switch-track">
                <span class="switch-thumb"></span>
              </span>
              <span class="lang-labels">
                <span class="lang-tr">TR</span>
                <span class="lang-en">EN</span>
              </span>
            </button>
          </div>
          
          <button type="button" class="appointment-btn" (click)="openAppointmentModal()">
            <span>{{ 'HEADER.NAV_APPOINTMENT' | translate }}</span>
            <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
              <path d="M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11zM7 10h5v5H7z"/>
            </svg>
          </button>
        </div>

        <!-- Mobile Menu Toggle -->
        <button
          class="mobile-menu-toggle"
          (click)="toggleMobileMenu()"
          aria-label="Toggle menu">
          <span [ngClass]="{'hamburger': true, 'active': isMobileMenuOpen}">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </button>
      </div>
    </div>
  </nav>
</header>

<!-- Mobile Menu Overlay -->
<div [ngClass]="{'mobile-menu': true, 'active': isMobileMenuOpen}">
  <div class="mobile-menu-header">
    <img src="/logos/OM-Wide-Color.svg" alt="Dr. Özlem Murzoğlu" />
    <button
      class="mobile-menu-close"
      (click)="toggleMobileMenu()"
      aria-label="Close menu">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
        <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
      </svg>
    </button>
  </div>
  <nav class="mobile-menu-nav">
    <div *ngFor="let item of primaryMenu" class="mobile-menu-item">
      <a [href]="item.href" class="mobile-menu-link" (click)="toggleMobileMenu()">
        {{ item.labelKey ? (item.labelKey | translate) : item.label }}
      </a>
      <div *ngIf="item.children" class="mobile-submenu">
        <a *ngFor="let child of item.children"
           [href]="child.href"
           class="mobile-submenu-link"
           (click)="toggleMobileMenu()">
          {{ child.labelKey ? (child.labelKey | translate) : child.label }}
        </a>
      </div>
    </div>
  </nav>
  <div class="mobile-menu-footer">
    <!-- Mobile Language Switcher -->
    <div class="language-switcher">
      <button 
        [ngClass]="{'switch-button': true, 'en-active': locale === 'en', 'animating': isAnimating}"
        (click)="handleLanguageChange()"
        aria-label="Change language">
        <span class="switch-track">
          <span class="switch-thumb"></span>
        </span>
        <span class="lang-labels">
          <span class="lang-tr">TR</span>
          <span class="lang-en">EN</span>
        </span>
      </button>
    </div>
    <button type="button" class="mobile-appointment-btn" (click)="openAppointmentModal()">
      {{ 'HEADER.NAV_APPOINTMENT' | translate }}
    </button>
  </div>
</div>

<!-- Appointment Modal -->
<app-appointment-modal 
  [isOpen]="isAppointmentModalOpen" 
  (close)="closeAppointmentModal()">
</app-appointment-modal>

// nextjs-backup/src/components/layout/Header.tsx
'use client'

import React, { useState, useEffect } from 'react'
import Link from 'next/link'
import { navigation, contactInfo } from '@/lib/navigation'
import { LanguageSwitcher } from '@/components/ui/LanguageSwitcher'

interface HeaderProps {
  locale?: string
}

const Header: React.FC<HeaderProps> = ({ locale = 'tr' }) => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)
  const [activeDropdown, setActiveDropdown] = useState<string | null>(null)

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 10)
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  useEffect(() => {
    if (isMobileMenuOpen) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = ''
    }
    return () => {
      document.body.style.overflow = ''
    }
  }, [isMobileMenuOpen])

  // Menü öğelerini grupla
  const primaryMenu = navigation.filter(item => 
    ['Ana Sayfa', 'Hakkımızda', 'Hizmetlerimiz', 'Makaleler', 'İletişim'].includes(item.label)
  )

  return (
    <>
      <header className={`modern-header ${isScrolled ? 'scrolled' : ''}`}>
        {/* Top Info Bar - Minimal */}
        <div className="top-bar">
          <div className="container">
            <div className="top-bar-content">
              <div className="contact-info">
                <a href={`tel:${contactInfo.phone}`} className="contact-link">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M20 15.5c-1.25 0-2.45-.2-3.57-.57a1.02 1.02 0 00-1.02.24l-2.2 2.2a15.045 15.045 0 01-6.59-6.59l2.2-2.21c.28-.26.36-.65.25-1.01A11.36 11.36 0 018.5 4c0-.55-.45-1-1-1H4c-.55 0-1 .45-1 1 0 9.39 7.61 17 17 17 .55 0 1-.45 1-1v-3.5c0-.55-.45-1-1-1z"/>
                  </svg>
                  {contactInfo.phone}
                </a>
                <span className="separator">•</span>
                <a href={`mailto:${contactInfo.email}`} className="contact-link">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/>
                  </svg>
                  {contactInfo.email}
                </a>
              </div>
              <a href="https://saglikpetegim.com" target="_blank" rel="noopener noreferrer" className="portal-link">
                Hasta Portalı →
              </a>
            </div>
          </div>
        </div>

        {/* Main Navigation */}
        <nav className="main-nav">
          <div className="container">
            <div className="nav-content">
              {/* Logo */}
              <Link href="/" className="logo">
                <img 
                  src="/logos/OM-Wide-Color.svg" 
                  alt="Dr. Özlem Murzoğlu" 
                  className="logo-wide"
                />
                <img 
                  src="/logos/OM-Icon-Color.svg" 
                  alt="Dr. Özlem Murzoğlu" 
                  className="logo-icon"
                />
              </Link>

              {/* Center Menu - Horizontal */}
              <div className="nav-menu">
                {primaryMenu.map((item) => (
                  <div
                    key={item.href}
                    className="nav-item"
                    onMouseEnter={() => item.children && setActiveDropdown(item.label)}
                    onMouseLeave={() => setActiveDropdown(null)}
                  >
                    <Link href={item.href} className="nav-link">
                      {item.label}
                      {item.children && (
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" className="dropdown-icon">
                          <path d="M7 10l5 5 5-5z"/>
                        </svg>
                      )}
                    </Link>
                    
                    {/* Dropdown Menu */}
                    {item.children && activeDropdown === item.label && (
                      <div className="dropdown-menu">
                        {item.children.map((child) => (
                          <Link
                            key={child.href}
                            href={child.href}
                            className="dropdown-link"
                          >
                            {child.label}
                          </Link>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>

              {/* Right Actions */}
              <div className="nav-actions">
                <LanguageSwitcher locale={locale} />
                <Link href="/randevu" className="appointment-btn">
                  <span>Randevu Al</span>
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11zM7 10h5v5H7z"/>
                  </svg>
                </Link>
              </div>

              {/* Mobile Menu Toggle */}
              <button
                className="mobile-menu-toggle"
                onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                aria-label="Toggle menu"
              >
                <span className={`hamburger ${isMobileMenuOpen ? 'active' : ''}`}>
                  <span></span>
                  <span></span>
                  <span></span>
                </span>
              </button>
            </div>
          </div>
        </nav>
      </header>

      {/* Mobile Menu Overlay */}
      <div className={`mobile-menu ${isMobileMenuOpen ? 'active' : ''}`}>
        <div className="mobile-menu-header">
          <img src="/logos/OM-Wide-Color.svg" alt="Dr. Özlem Murzoğlu" />
          <button
            className="mobile-menu-close"
            onClick={() => setIsMobileMenuOpen(false)}
            aria-label="Close menu"
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
              <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
            </svg>
          </button>
        </div>
        <nav className="mobile-menu-nav">
          {primaryMenu.map((item) => (
            <div key={item.href} className="mobile-menu-item">
              <Link href={item.href} className="mobile-menu-link" onClick={() => setIsMobileMenuOpen(false)}>
                {item.label}
              </Link>
              {item.children && (
                <div className="mobile-submenu">
                  {item.children.map((child) => (
                    <Link
                      key={child.href}
                      href={child.href}
                      className="mobile-submenu-link"
                      onClick={() => setIsMobileMenuOpen(false)}
                    >
                      {child.label}
                    </Link>
                  ))}
                </div>
              )}
            </div>
          ))}
        </nav>
        <div className="mobile-menu-footer">
          <LanguageSwitcher locale={locale} />
          <Link href="/randevu" className="mobile-appointment-btn" onClick={() => setIsMobileMenuOpen(false)}>
            Randevu Al
          </Link>
        </div>
      </div>

      <style jsx>{`
        /* Header Container */
        .modern-header {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          background: #FFFFFF;
          box-shadow: 0 2px 8px rgba(0, 95, 115, 0.08);
          z-index: 1000;
          transition: all 0.3s ease;
        }

        .modern-header.scrolled {
          box-shadow: 0 4px 20px rgba(0, 95, 115, 0.12);
        }

        /* Top Bar */
        .top-bar {
          background: linear-gradient(135deg, #005F73 0%, #0A8FA3 100%);
          color: white;
          padding: 6px 0;
          font-size: 13px;
        }

        .container {
          max-width: 1400px;
          margin: 0 auto;
          padding: 0 24px;
        }

        .top-bar-content {
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .contact-info {
          display: flex;
          align-items: center;
          gap: 16px;
        }

        .contact-link {
          display: flex;
          align-items: center;
          gap: 6px;
          color: white;
          text-decoration: none;
          transition: opacity 0.2s;
        }

        .contact-link:hover {
          opacity: 0.9;
        }

        .contact-link svg {
          opacity: 0.9;
        }

        .separator {
          opacity: 0.4;
        }

        .portal-link {
          color: white;
          text-decoration: none;
          font-weight: 500;
          transition: all 0.2s;
          padding: 4px 12px;
          border-radius: 4px;
          background: rgba(255, 255, 255, 0.1);
        }

        .portal-link:hover {
          background: rgba(255, 255, 255, 0.2);
        }

        /* Main Navigation */
        .main-nav {
          background: white;
          padding: 16px 0;
          border-bottom: 1px solid rgba(0, 95, 115, 0.08);
        }

        .nav-content {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 48px;
        }

        /* Logo */
        .logo {
          display: flex;
          align-items: center;
          flex-shrink: 0;
        }

        .logo img {
          height: 48px;
          width: auto;
          transition: height 0.3s;
          object-fit: contain;
        }

        .modern-header.scrolled .logo img {
          height: 40px;
        }

        .logo-wide {
          display: block;
          max-width: 200px;
        }

        .logo-icon {
          display: none;
        }

        /* Center Menu */
        .nav-menu {
          display: none;
          align-items: center;
          gap: 8px;
          flex: 1;
          justify-content: center;
        }

        @media (min-width: 1024px) {
          .nav-menu {
            display: flex;
          }
        }

        .nav-item {
          position: relative;
        }

        .nav-link {
          display: flex;
          align-items: center;
          gap: 4px;
          padding: 10px 16px;
          margin: 0 4px;
          color: var(--md-sys-color-on-surface);
          text-decoration: none;
          font-size: 15px;
          font-weight: 500;
          white-space: nowrap;
          border-radius: 12px;
          transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
          position: relative;
        }

        .nav-link::after {
          content: '';
          position: absolute;
          bottom: 4px;
          left: 16px;
          right: 16px;
          height: 3px;
          background: linear-gradient(90deg, #FFB74D, #FFA726);
          border-radius: 2px;
          transform: scaleX(0);
          transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .nav-link:hover {
          color: #005F73;
          background: rgba(0, 95, 115, 0.04);
        }

        .nav-link:hover::after {
          transform: scaleX(1);
        }

        .dropdown-icon {
          margin-left: 2px;
          transition: transform 0.3s;
        }

        .nav-item:hover .dropdown-icon {
          transform: rotate(180deg);
        }

        /* Dropdown Menu */
        .dropdown-menu {
          position: absolute;
          top: calc(100% + 8px);
          left: 50%;
          transform: translateX(-50%);
          background: white;
          border-radius: 16px;
          box-shadow: 0 8px 32px rgba(0, 95, 115, 0.15);
          padding: 8px;
          min-width: 260px;
          opacity: 0;
          transform: translateX(-50%) translateY(-10px);
          animation: dropdownSlide 0.3s ease forwards;
          border: 1px solid rgba(0, 95, 115, 0.08);
          z-index: 1000;
        }

        @keyframes dropdownSlide {
          to {
            opacity: 1;
            transform: translateX(-50%) translateY(0);
          }
        }

        .dropdown-link {
          display: block;
          padding: 12px 16px;
          margin: 2px 0;
          color: var(--md-sys-color-on-surface);
          text-decoration: none;
          font-size: 14px;
          border-radius: 8px;
          transition: all 0.2s;
          white-space: nowrap;
          line-height: 1.4;
        }

        .dropdown-link:hover {
          background: linear-gradient(135deg, rgba(255, 183, 77, 0.1), rgba(255, 167, 38, 0.1));
          color: #005F73;
          padding-left: 20px;
        }

        /* Right Actions */
        .nav-actions {
          display: none;
          align-items: center;
          gap: 16px;
        }

        @media (min-width: 1024px) {
          .nav-actions {
            display: flex;
          }
        }

        .appointment-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 24px;
          background: linear-gradient(135deg, #FFB74D 0%, #FFA726 100%);
          color: #005F73;
          text-decoration: none;
          font-weight: 600;
          font-size: 15px;
          border-radius: 28px;
          transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
          box-shadow: 0 4px 12px rgba(255, 167, 38, 0.3);
        }

        .appointment-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 6px 20px rgba(255, 167, 38, 0.4);
          background: linear-gradient(135deg, #FFA726 0%, #FF9800 100%);
        }

        .appointment-btn svg {
          transition: transform 0.3s;
        }

        .appointment-btn:hover svg {
          transform: rotate(15deg);
        }

        /* Mobile Menu Toggle */
        .mobile-menu-toggle {
          display: flex;
          align-items: center;
          justify-content: center;
          width: 40px;
          height: 40px;
          background: transparent;
          border: none;
          cursor: pointer;
          padding: 0;
        }

        @media (min-width: 1024px) {
          .mobile-menu-toggle {
            display: none;
          }
        }

        .hamburger {
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          width: 24px;
          height: 24px;
          position: relative;
        }

        .hamburger span {
          display: block;
          width: 100%;
          height: 2px;
          background: var(--md-sys-color-on-surface);
          border-radius: 2px;
          transition: all 0.3s;
          position: absolute;
        }

        .hamburger span:nth-child(1) {
          top: 6px;
        }

        .hamburger span:nth-child(2) {
          top: 50%;
          transform: translateY(-50%);
        }

        .hamburger span:nth-child(3) {
          bottom: 6px;
        }

        .hamburger.active span:nth-child(1) {
          top: 50%;
          transform: translateY(-50%) rotate(45deg);
        }

        .hamburger.active span:nth-child(2) {
          opacity: 0;
        }

        .hamburger.active span:nth-child(3) {
          bottom: 50%;
          transform: translateY(50%) rotate(-45deg);
        }

        /* Mobile Menu */
        .mobile-menu {
          position: fixed;
          top: 0;
          right: -100%;
          width: 100%;
          max-width: 400px;
          height: 100vh;
          background: white;
          box-shadow: -4px 0 24px rgba(0, 0, 0, 0.1);
          z-index: 1001;
          transition: right 0.3s ease;
          overflow-y: auto;
        }

        .mobile-menu.active {
          right: 0;
        }

        .mobile-menu-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 20px;
          border-bottom: 1px solid rgba(0, 95, 115, 0.1);
        }

        .mobile-menu-header img {
          height: 32px;
        }

        .mobile-menu-close {
          background: transparent;
          border: none;
          cursor: pointer;
          padding: 8px;
        }

        .mobile-menu-nav {
          padding: 20px;
        }

        .mobile-menu-item {
          margin-bottom: 8px;
        }

        .mobile-menu-link {
          display: block;
          padding: 12px 16px;
          color: var(--md-sys-color-on-surface);
          text-decoration: none;
          font-size: 16px;
          font-weight: 500;
          border-radius: 8px;
          transition: background 0.2s;
        }

        .mobile-menu-link:hover {
          background: rgba(0, 95, 115, 0.05);
        }

        .mobile-submenu {
          margin-top: 4px;
          margin-left: 16px;
          padding-left: 16px;
          border-left: 2px solid rgba(0, 95, 115, 0.1);
        }

        .mobile-submenu-link {
          display: block;
          padding: 8px 12px;
          color: var(--md-sys-color-on-surface-variant);
          text-decoration: none;
          font-size: 14px;
          border-radius: 6px;
          transition: background 0.2s;
        }

        .mobile-submenu-link:hover {
          background: rgba(255, 183, 77, 0.1);
        }

        .mobile-menu-footer {
          padding: 20px;
          border-top: 1px solid rgba(0, 95, 115, 0.1);
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .mobile-appointment-btn {
          display: block;
          text-align: center;
          padding: 14px 24px;
          background: linear-gradient(135deg, #FFB74D 0%, #FFA726 100%);
          color: #005F73;
          text-decoration: none;
          font-weight: 600;
          font-size: 16px;
          border-radius: 28px;
          transition: all 0.2s;
        }

        .mobile-appointment-btn:hover {
          background: linear-gradient(135deg, #FFA726 0%, #FF9800 100%);
        }

        /* Responsive adjustments */
        @media (max-width: 768px) {
          .top-bar {
            display: none;
          }

          .main-nav {
            padding: 12px 0;
          }

          .logo-wide {
            display: none;
          }

          .logo-icon {
            display: block;
            height: 36px;
          }

          .container {
            padding: 0 16px;
          }
        }
      `}</style>
    </>
  )
}

export { Header }
